fix: trip ratings not showing
afonsosousah/mGira pull request #16
Opened 2024-01-30 22:57 UTC by afonsosousah

Ratings were not being prompted since the major refactoring.
An undefined object was behaving erraticaly in an if statement.

Also the rate trip menu UI was improved, switched to a truly responsive layout.

2024-02-10 18:56 UTC, ImRodry requested changes

2024-02-10 18:56 UTC, ImRodry commented on scripts/bikes.js
neste caso podes fazer isso porque no caso de startsInput ser falsy dás return então isto vai sempre ter o valor real
```suggestion
	const tripRating = Number(starsInput?.value);
	if (starsInput) {
```

2024-02-10 18:56 UTC, ImRodry commented on scripts/bikes.js
> +		}, 1000);
porque o delay?

2024-02-10 18:56 UTC, ImRodry commented on scripts/bikes.js
>  	if (tripRating <= 3) {
eu sei que a app oficial só pede abaixo de 3 mas podemos subir isto para 4? Para mim nunca me fez sentido ter de ser abaixo de 3 mas compreendo se nao quiseres mudar

2024-02-10 19:00 UTC, afonsosousah commented on scripts/bikes.js
> +		}, 1000);
estava a dar um erro, a função de dar rate não conseguia aceder ao número de estrelas porque o menu tinha sido removed, 1s é probably overkill, mas é para estar safe

2024-02-10 19:01 UTC, afonsosousah commented on scripts/bikes.js
>  	if (tripRating <= 3) {
imagina, acho que uma pessoa que tenha dado 4 estrelas não tem a necessidade de enviar um comentário, mas uma pessoa que tenha dado 3 já faz sentido

2024-02-11 00:38 UTC, ImRodry commented on scripts/bikes.js
>  	if (tripRating <= 3) {
eu acho que qualquer coisa diferente de 5 é uma viagem que teve algum tipo de problema, logo pode ser relatado, mas podemos ver isso noutra altura, não tem de ser neste PR

2024-02-11 00:40 UTC, ImRodry commented on scripts/bikes.js
> +		}, 1000);
Inicialmente o erro era porque a função estava a ser chamada novamente quando era suposto ser chamada a API, o que já foi corrigido. Depois disso estar corrigido não vejo porque é que daria esse erro, já testaste? De qualquer forma um delay de 50 ou 100 seria melhor

2024-02-11 20:13 UTC, ImRodry commented on scripts/bikes.js
> +		}, 1000);
```suggestion
		if (document.getElementById("rateTripMenu")) document.getElementById("rateTripMenu").remove();
```

2024-02-11 20:13 UTC, ImRodry approved these changes

2024-02-11 20:14 UTC, merged