fix: better token refresh, removed forgotten console logs
afonsosousah/mGira pull request #21
Opened 2024-02-17 02:35 UTC by afonsosousah

Melhorei um pouco o sistema dos token refresh:
- mudei o número de tentativas de 5 para 3 (número arbitrário, necessário feedback)
- substitui o sistema de uma função de checkToken com um callback para um sistema de promises, assim várias chamadas à tokenRefresh simultâneas respondem da forma correta (é apenas criada uma promise que é devolvida várias vezes até ela estar fulfilled)
- removi alguns console.log sem nenhuma utilidade aparente

2024-02-19 17:59 UTC, ImRodry commented
rebased

2024-02-22 00:00 UTC, afonsosousah commented
rebased

2024-02-23 22:22 UTC, afonsosousah commented on proxy.php
as alterações ao ficheiro proxy.php são apenas de formatação do prettier

2024-02-23 22:31 UTC, afonsosousah commented on scripts/requests.js
> -			Priority: "high",
Retirei estes fields porque não tinham utilidade

2024-02-23 22:31 UTC, afonsosousah commented on scripts/requests.js
> -}
com o novo sistema de promises, esta função deixa de ser necessária

2024-02-25 01:45 UTC, ImRodry requested changes

2024-02-25 01:45 UTC, ImRodry commented on scripts/requests.js
> -			Priority: "high",
se a app oficial manda o user-agent eu acho importante manter. A priority é igual até porque acho que esse header não é standard ou não deve servir para nada

2024-02-25 01:45 UTC, ImRodry commented on scripts/requests.js
> +		}
este código não é duplicado de outro sítio?

2024-02-25 01:45 UTC, ImRodry commented on scripts/requests.js
> +		if (typeof accessToken !== "undefined") {
eu vou te bater por cada typeof eu juro

2024-02-25 01:45 UTC, ImRodry commented on scripts/tokenRefresh.js
> +	if (tokenPromise !== null) return tokenPromise;
```suggestion
	if (tokenPromise) return tokenPromise;
```

2024-02-25 01:45 UTC, ImRodry commented on scripts/tokenRefresh.js
> +					"X-Proxy-URL": "https://api-auth.emel.pt/token/refresh",
não era suposto isto nao passar pela proxy?

2024-02-25 01:45 UTC, ImRodry commented on scripts/user.js
> +		body: JSON.stringify({
o que é que faz dar bypass aqui que nao pode ser feito nos outros?

2024-02-25 01:45 UTC, ImRodry commented on scripts/user.js
> +		startLocationDotRotation();
isto aparece no map, porquê 2x?

2024-02-25 01:45 UTC, ImRodry commented on scripts/user.js
> +	document.cookie = 'accessToken=None;path="/";expires=Thu, 01 Jan 1970 00:00:01 GMT'; // delete cookie
podes simplesmente usar new Date(0).toUTCString()
e já agora apagar aquele comment?

2024-02-25 18:33 UTC, afonsosousah commented on scripts/user.js
> +		body: JSON.stringify({
estou simplesmente a usar o fetch diretamente

2024-02-25 18:34 UTC, afonsosousah commented on index.html
> +				proxyURL = "https://corsproxy.afonsosousah.workers.dev/";
i think so

2024-02-25 18:36 UTC, afonsosousah commented on index.html
> +				proxyURL = "https://corsproxy.afonsosousah.workers.dev/";
```suggestion
				proxyURL = null;
```

2024-02-25 18:38 UTC, afonsosousah commented on scripts/bikes.js
>  }
é necessário apenas 2x, tem vezes a mais

2024-02-25 18:41 UTC, afonsosousah commented on scripts/map.js
> +	// Check if the user is logged in, if not, prompt to login
ups, reutilizei o código e o comment também, pelos vistos

2024-02-25 18:41 UTC, afonsosousah commented on scripts/map.js
> +	// Check if the user is logged in, if not, prompt to login
```suggestion
	// Check if the user has a stored access token
```

2024-02-25 18:43 UTC, afonsosousah commented on scripts/requests.js
> +		}
é igual ao caso do "Error executing document"

2024-02-25 18:45 UTC, afonsosousah commented on scripts/requests.js
> +		if (typeof accessToken !== "undefined") {
nem reparei, veio de cima, do makePostRequest

2024-02-25 18:46 UTC, afonsosousah commented on scripts/requests.js
> +		if (typeof accessToken !== "undefined") {
```suggestion
		if (accessToken) {
```

2024-02-25 18:47 UTC, afonsosousah commented on scripts/tokenRefresh.js
> +					"X-Proxy-URL": "https://api-auth.emel.pt/token/refresh",
tenho de ver se tem headers do CORS, mas acho que ya, não precisa do proxy

2024-02-25 18:50 UTC, afonsosousah commented on scripts/tokenRefresh.js
> +					"X-Proxy-URL": "https://api-auth.emel.pt/token/refresh",
```suggestion
			const response = await fetch("https://api-auth.emel.pt/token/refresh", {
				method: "POST",
				headers: {
```

2024-02-25 18:51 UTC, afonsosousah commented on scripts/user.js
> +		startLocationDotRotation();
porque se o user não tiver o login feito, as startup functions não correm por não ter access token ainda

2024-02-25 18:53 UTC, afonsosousah commented on scripts/user.js
> +	document.cookie = 'accessToken=None;path="/";expires=Thu, 01 Jan 1970 00:00:01 GMT'; // delete cookie
o new Date não é expensive?

2024-02-25 18:53 UTC, afonsosousah commented on scripts/user.js
> +	//document.cookie = "version=0.0.0"; // Force show update notes after logout
```suggestion

```

2024-02-25 20:08 UTC, afonsosousah commented
rebased

2024-02-25 22:13 UTC, ImRodry commented on scripts/bikes.js
>  }
eu acho que agora tá bom só podias era meter depois da chamada da função

2024-02-25 22:13 UTC, ImRodry commented on scripts/requests.js
> +		}
então mete tudo no mesmo bloco

2024-02-25 22:13 UTC, ImRodry commented on scripts/user.js
> +		body: JSON.stringify({
ok mas porque é que não podes fazer isto em todos os casos? Não seria melhor nunca passar pela proxy?

2024-02-25 22:13 UTC, ImRodry commented on scripts/user.js
> +		startLocationDotRotation();
e não devia ser assim? Só vais carregar estações e assim depois do login. Mesmo o dar zoom na localização e isso tudo pode so vir depois

2024-02-25 22:13 UTC, ImRodry commented on scripts/user.js
> +	document.cookie = 'accessToken=None;path="/";expires=Thu, 01 Jan 1970 00:00:01 GMT'; // delete cookie
bem visto

2024-02-26 00:23 UTC, afonsosousah commented on scripts/requests.js
> -			Priority: "high",
concordo em manter o user agent, a versão da Gira é que talvez tenha de ser atualizada

2024-02-26 00:23 UTC, afonsosousah commented on scripts/user.js
> +		body: JSON.stringify({
os pedidos à apigira não dão para realizar sem um proxy pois a API não server headers de CORS

2024-02-26 00:25 UTC, afonsosousah commented on scripts/user.js
> +		startLocationDotRotation();
é isso que está a acontecer, tem de estar repetido no user precisamente para que isso aconteça

2024-03-02 20:12 UTC, afonsosousah commented
rebased

2024-03-02 22:51 UTC, afonsosousah commented on scripts/bikes.js
>  }
estive agora a dar uma vista de olhos, e até faz sentido estar onde está.
só corre depois do user ter deixado opcionalmente feedback

2024-03-11 19:53 UTC, merged