feat: starting horizontal support
afonsosousah/mGira pull request #34
Opened 2024-03-16 23:30 UTC by afonsosousah

Adiciona um layout para o ecrã horizontal, permitindo que a app seja utilizada em modo landscape no suporte de telemóvel da bicicleta, sem que esteja em navegação.
De momento a 3D view não será implementada neste modo, pois não é possível carregar nos pontos das estações no mapa.
Remove a necessidade do aviso de rodar o ecrã.

To-do:
- [ ] Place search menu
- [ ] Rate trip menu
- [ ] Take unregistered bike
- [ ] Trip history
- [ ] Statistics menu

2024-03-23 01:15 UTC, afonsosousah commented
rebase

2024-03-25 02:18 UTC, afonsosousah commented
rebased

2024-03-25 17:26 UTC, afonsosousah commented
rebased

2024-03-31 02:03 UTC, ImRodry requested changes

2024-03-31 02:03 UTC, ImRodry commented on scripts/routing.js
> +	const convertedBbox = [Xmin, Ymin, Xmax, Ymax];
```suggestion
	const xMin = Math.min(bboxFoot1[0], bboxBike[0], bboxFoot2[0]);
	const yMin = Math.min(bboxFoot1[1], bboxBike[1], bboxFoot2[1]);
	const xMax = Math.max(bboxFoot1[2], bboxBike[2], bboxFoot2[2]);
	const yMax = Math.max(bboxFoot1[3], bboxBike[3], bboxFoot2[3]);

	const convertedBbox = [xMin, yMin, xMax, yMax];
```

2024-03-31 02:03 UTC, ImRodry commented on scripts/routing.js
> +			if (!response || (response && response.features.length === 0)) {
se estás a ver antes se é falsy, para quê ver logo a seguir se é truthy?
```suggestion
			if (!response || response.features.length === 0) {
```

2024-03-31 02:03 UTC, ImRodry commented on scripts/routing.js
> +		.filter(layer => layer.get("name") === "placesLayer" || layer.get("name") === "routeLayer")
```suggestion
		.filter(layer => ["placesLayer", "routeLayer"].includes(layer.get("name")))
```

2024-03-31 17:00 UTC, afonsosousah commented on scripts/navigation.js
> +	if (window.matchMedia("(orientation: landscape)").matches) showRotationNotice();
em navegação a pé ficou assim, só porque acho um bocado estranho ter o telemóvel na horizontal para navegar a pé.
mas valid point

2024-04-01 00:14 UTC, ImRodry commented on scripts/navigation.js
> +	if (window.matchMedia("(orientation: landscape)").matches) showRotationNotice();
mas porque é que tens de limitar a escolha das pessoas? Podes preferir usar assim e permitir as duas na mesma, e da forma como isto tá feito não sei se haveria muita coisa a mudar

2024-04-10 19:00 UTC, afonsosousah commented on scripts/navigation.js
> +	if (typeof document.body.requestFullscreen === "function") document.body.requestFullscreen();
```suggestion
	// https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen
	if (typeof document.body.requestFullscreen === "function") document.body.requestFullscreen();
```

2024-04-10 19:01 UTC, afonsosousah commented on scripts/navigation.js
> +		<div id="speed">0</div>
```suggestion
		<div id="speed">N/A</div>
```

2024-04-10 19:02 UTC, afonsosousah commented on scripts/navigation.js
> +		const userPosition = ol.proj.fromLonLat(pos);
Lê o comment xd

2024-04-10 19:03 UTC, afonsosousah commented on scripts/navigation.js
> +			document.querySelector("#rotateScreenNotice").remove();
where?

2024-04-10 19:05 UTC, afonsosousah commented on scripts/navigation.js
> +		wakeLock = await navigator.wakeLock.request("screen");
acho que é um pouco hit or miss. para mim tenho a impressão que até tem funcionado

2024-04-10 19:07 UTC, afonsosousah commented on scripts/navigation.js
> +	rotationMode = "free";
o pensamento era que se esse for o default, o user não conseguiria mexer o mapa, mas após pensar um bocadinho, diria que dá para fazer isto de melhor forma tendo um listener para quando o user mexe no mapa para deixar de seguir

2024-04-10 19:08 UTC, afonsosousah commented on scripts/navigation.js
> +		const navigationElements = Array.from(document.querySelectorAll("*")).filter(
não sei mesmo se há melhor, penso que não dê para fazer isto logo no querySelector

2024-04-10 19:09 UTC, afonsosousah commented on scripts/routing.js
> +		routeSummaryFoot2 = await calculateRoute([dropoffStation.longitude, dropoffStation.latitude], toCoordinates, false);
não são globais, estão definidas dentro da função. simplesmente vão mudando de valor

2024-04-10 19:09 UTC, afonsosousah commented on scripts/routing.js
> +			if (!response || (response && response.features.length === 0)) {
tinha escrito a condição da direita primeiro xd

2024-04-10 19:22 UTC, afonsosousah commented on scripts/map.js
> +		} else if (station.docks !== 0 && showDocks) {
fixed in latest commit

2024-04-10 19:23 UTC, afonsosousah commented on scripts/navigation.js
> +	if (window.matchMedia("(orientation: landscape)").matches) showRotationNotice();
true, vou tentar implementar isto para funcionar tudo em qualquer orientação

2024-04-10 19:33 UTC, afonsosousah commented on scripts/navigation.js
>  			changeRotationModeButtonPortrait.innerHTML = `<i class="bi bi-sign-turn-right"></i>`;
fixed in [902d282](https://github.com/afonsosousah/mGira/pull/34/commits/902d282f6a353b109849230a1dc1bbc460495ba2)

2024-04-22 21:03 UTC, afonsosousah commented
rebased

2024-04-23 23:38 UTC, afonsosousah commented
rebased

2024-04-24 00:13 UTC, merged